### ISSUE TITLE
Feature request: Put controllers in custom package

### ISSUE THREAD

**Issue by yngvark** [swagger-api/swagger-inflector#263]
Swagger Inflector forces you to put all your controllers in a single package, for instance "com.example.controllers".

This makes it impossible to follow package-by-feature (http://www.javapractices.com/topic/TopicAction.do?Id=205). For example, I want to have `com.example.manage_users.UserController` and `com.example.add_orders.OrderController`.

I'm sure there are other use cases, and enforcing all controllers to be put in a single package is a bit strict.

I have read the documentation and be doing some debugging, but not found a workaround for this.

Any thoughts?

**Comment by fehguy** [comment]
You can specify the package for each function:

```
paths:
  /health:
    get:
      description: Provides a simple health check
      operationId: healthCheck
      x-swagger-router-controller: com.foo.bar.HealthController
```

Doesn't that solve your concern?
